INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte inferior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','core','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte superior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte inferior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte inferior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','core','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','core','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte superior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','parte superior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte inferior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','core','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte superior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte inferior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte inferior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','core','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','core','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte superior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','parte superior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte inferior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte inferior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte inferior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte superior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte superior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','parte superior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','core','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','core','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Cardio','core','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte inferior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte inferior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte inferior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte superior','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte superior','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','parte superior','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','core','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','core','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','core','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Calentamiento','Completo','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Calentamiento','Completo','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','Completo','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','Completo','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Fuerza','Completo','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','Completo','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','Completo','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('Equilibrio','Completo','bajo impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','Completo','alto impacto');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','Completo','medio');
INSERT INTO ejercicio(tipo_entrenamiento,parte_del_cuerpo,dificultad) VALUES ('flexibilidad','Completo','bajo impacto');
INSERT INTO cliente(cliente_cc,nombre1_cliente,apellido1_cliente,apellido2_cliente, objetivo) VALUES('1022416224','rodrigo','castillo','camargo','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1001911197','jhan','carlos','celi','maldonado','Ganar Masa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1000580668','andres','felipe','florian','quitian','Comenzar');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1049657682','daniel','jose','forero','corredor','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1006097260','sara','lucia','gallego','rivera','Ganar Masa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1006130987','maria','paula','gaviria','perez','Comenzar');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1193390038','andrey','javier','lizarazo','hernandez','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1001309550','joseph','daniel','mancera','basto','Ganar Masa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,apellido1_cliente,apellido2_cliente, objetivo) VALUES('1002776873','isabella','martinez','martinez','Comenzar');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1006108401','carlos','sebastian','martinez','vidal','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1020833401','david','santiago','moreno','medina','Ganar Masa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1000718139','daniel','andres','navarrete','uribe','Comenzar');
INSERT INTO cliente(cliente_cc,nombre1_cliente,apellido1_cliente,apellido2_cliente, objetivo) VALUES('1010247531','sara','palacios','chavarro','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1000158935','victor','manuel','sicacha','cardenas','Ganar Masa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,apellido1_cliente,apellido2_cliente, objetivo) VALUES('1001184355','santiago','uribe','luna','Comenzar');
INSERT INTO cliente(cliente_cc,nombre1_cliente,apellido1_cliente,apellido2_cliente, objetivo) VALUES('1003557913','oscar','velasco','chiquillo','Reducir Grasa');
INSERT INTO cliente(cliente_cc,nombre1_cliente,nombre2_cliente, apellido1_cliente, apellido2_cliente, objetivo) VALUES('1001199728','maria','salome','viana','cano','Comenzar');
